### ISSUE TITLE
Tensorflow Version

### ISSUE THREAD

**Issue by Karric** [1jz/stable-diffusion-scaler#1]
Would you be willing to create a tensorflow version of this? I'm on an Apple Silicon machine, so Torch is very difficult to install properly. Looking at the script, it seems like you're just using it to create the seed?

**Comment by 1jz** [comment]
Hey, I am using [diffusers](https://github.com/huggingface/diffusers) in this script which only work with Torch/Flax I am only directly interacting with Torch to set the seed globally for every iteration to ensure each segment uses the same seed for upscaling.

I don't exactly have the time to support different platforms, all the script is really doing is segmenting an image and stitching it back together, so you can take `segment_img` and `merge_segments` and use it with a tensorflow implementation of stable diffusion.
